### ISSUE TITLE
closed.

### ISSUE THREAD

**Issue by jaydickinson** [muhajirframe/gatsby-tailwind-emotion-starter#1]
wrong thread.

**Comment by muhajirdev** [comment]
Hey @jaydickinson , thank you for submitting the issue. Is the transition you mean like in https://muhajirframe.com . 

If it is, I'd happily write the tutorial for that :)

**Comment by jaydickinson** [comment]
Yeah, but I found a gatsby plugin for it and posted this in the wrong thread sorry! :) am using tailwind and gatsby though its great!

**Comment by muhajirdev** [comment]
Ah, nice to hear that @jaydickinson 👍
